keys:
  # Users
  - &users:
    - &luxus age1ncepfcrzfep624tpanhqfflafznh7ftuqffv0nfq24jhv3dwx40sltjkad
  # Hosts
  - &hosts:
    - &cecile age1ncepfcrzfep624tpanhqfflafznh7ftuqffv0nfq24jhv3dwx40sltjkad
creation_rules:
  - path_regex: secrets/cecile.ya?ml$
    key_groups:
    - age:
      - *luxus
